### ISSUE TITLE
Entities not showing up

### ISSUE THREAD

**Issue by Mephphisto** [g4bri3lDev/munich_public_transport#5]
I used the example config
```
# Example configuration.yaml entry
sensor:
  - platform: mvglive
    nextdeparture:
     - station: Hauptbahnhof
       name: Hbf
       destinations: ['München Flughafen Terminal','Markt Schwaben']
       products: "S-Bahn"
       timeoffset: 2
     - station: Sendlinger Tor
       lines: ['U2','U8']
       number: 5
     - station: Scheidplatz
       products: ['U-Bahn']
       directions: "1"
```
and the entities are not showing up
